from pathlib import Path
from typing import Protocol

from wks_core.domain.models import ExtractedRepresentation


class ObjectStore(Protocol):
    def put_file(self, key: str, path: Path) -> None: ...
    def materialize(self, key: str, destination: Path) -> None: ...
    def iter_bytes(self, key: str, start: int = 0, end: int | None = None): ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
    def ready(self) -> bool: ...


class SourceProcessor(Protocol):
    def extract(self, path: Path, media_type: str) -> ExtractedRepresentation: ...


class MediaEnricher(Protocol):
    def enrich(self, content: bytes, media_type: str, operation_id: str) -> dict: ...
